service: layer-test
useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'local'}
  region: us-east-2

layers:
  chrome:
    path: layer

functions:
  makePdf:
    handler: src/handlers/handler.makePdf
    memorySize: 1536 # RAM size for the function
    timeout: 15
    layers: 
      - { Ref: ChromeLambdaLayer }
      # - arn:aws:lambda:us-east-2:764866452798:layer:chrome-aws-lambda:25
    events:
      - http:
          path: /makePdf
          method: post

